//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemShipment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<System.DateTime> ExperiedTime { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Supplier_id { get; set; }
        public int StoreItem_id { get; set; }
    
        public virtual StoreItem StoreItem { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
