//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreItem
    {
        public StoreItem()
        {
            this.FoodIngredients = new HashSet<FoodIngredient>();
            this.ItemShipments = new HashSet<ItemShipment>();
            this.StoreConsumptions = new HashSet<StoreConsumption>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CurrentCount { get; set; }
        public Nullable<int> RequiredCount { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int ItemType_ID { get; set; }
    
        public virtual ICollection<FoodIngredient> FoodIngredients { get; set; }
        public virtual ICollection<ItemShipment> ItemShipments { get; set; }
        public virtual ICollection<StoreConsumption> StoreConsumptions { get; set; }
        public virtual StoreItemType StoreItemType { get; set; }
    }
}
