//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPrivilege
    {
        public int ID { get; set; }
        public Nullable<int> Screen_id { get; set; }
        public Nullable<int> UserType_id { get; set; }
    
        public virtual Screen Screen { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
