//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        public Screen()
        {
            this.UserPrivileges = new HashSet<UserPrivilege>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Describtion { get; set; }
    
        public virtual ICollection<UserPrivilege> UserPrivileges { get; set; }
    }
}
